### ISSUE TITLE
Wall Glitch Bug.

### ISSUE THREAD

**Issue by Minirals** [Rookitmin/ICS2O.SUM.RD.BM.AHA#14]
Player can move through walls with proper timing. Fix: Required.

**Comment by Minirals** [comment]
I shall find the exact conditions of the bug.

**Comment by Rookitmin** [comment]
by moving towards one wall, and pressing the button to move away from the wall at the moment where the player hits the wall, the player passes through the wall.

**Comment by Minirals** [comment]
It appears to have some sort of distance requirement, as it seems to need a good run up before it works. It still sometimes occurs randomly.

**Comment by Minirals** [comment]
Thanks to recent updates, this glitch is even more game breaking. Also the puck has decided that it likes to leave the arena.

**Comment by Minirals** [comment]
Ok, this issue really does not matter that much, and is hard to trigger without knowing of the glitch before hand.
