### ISSUE TITLE
Pause Menu Settings Bug.

### ISSUE THREAD

**Issue by Minirals** [Rookitmin/ICS2O.SUM.RD.BM.AHA#15]
The settings tab in the pause menu still has the bug from the pause menu.

**Comment by Rookitmin** [comment]
working on it - R
\- just an FYI, the menu screen is still in progress

**Comment by Rookitmin** [comment]
Ok, the code has been updated. check now for me, will you?

**Comment by Minirals** [comment]
AGGRESSIVE PLAY TESTING TIME.

**Comment by Minirals** [comment]
Yeahhhh. The issue is really not fixed. The settings tab still locks you out of everything else, and the change team button does exactly what settings used to do.

**Comment by Rookitmin** [comment]
This should be not broken now.

**Comment by Minirals** [comment]
Yeah they good. ISSUE CLOSED!
