### ISSUE TITLE
Code Animations

### ISSUE THREAD

**Issue by Rookitmin** [Rookitmin/ICS2O.SUM.RD.BM.AHA#3]
- [x] menu screen
- [x] pause screen
- [x] in game screen

**Comment by Rookitmin** [comment]
Bots? or limit to two players?

**Comment by Rookitmin** [comment]
@Ali596087 @Minirals Should we?

**Comment by Minirals** [comment]
Bots is a lot of work, but we do not have enough space on the keyboard for more players. Also, it would make most of the buttons do something if we had bots.

**Comment by Rookitmin** [comment]
I meant, should we make the game only playable with two players?

**Comment by Minirals** [comment]
If we cannot do bots, then yes.

**Comment by Ali596087** [comment]
Two players

**Comment by Rookitmin** [comment]
Two Players It IS!

**Comment by Ali596087** [comment]
!!!

**Comment by Minirals** [comment]
Standing by to remove the last issue.
